/**
 * Todo
 * API of the worlds most advanced Todo app.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TodoItem } from './todoItem';


export interface TodoList {
    id?: number;
    name?: string;
    userId?: number;
    todoItems?: Array<TodoItem>;
}
