/**
 * Todo
 * API of the worlds most advanced Todo app.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TodoItem {
    id?: number;
    name?: string;
    description?: string;
    due?: Date;
    done?: boolean;
}
