/**
 * Todo
 * API of the worlds most advanced Todo app.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { TodoItem } from '../model/todoItem';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TodoItemService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *
     * @param listId
     * @param id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTodoListByListIdTodoItemByIdDelete(listId: number, id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiTodoListByListIdTodoItemByIdDelete(listId: number, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiTodoListByListIdTodoItemByIdDelete(listId: number, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiTodoListByListIdTodoItemByIdDelete(listId: number, id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (listId === null || listId === undefined) {
            throw new Error('Required parameter listId was null or undefined when calling apiTodoListByListIdTodoItemByIdDelete.');
        }
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiTodoListByListIdTodoItemByIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/todoList/${encodeURIComponent(String(listId))}/TodoItem/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param listId
     * @param id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTodoListByListIdTodoItemByIdGet(listId: number, id: number, observe?: 'body', reportProgress?: boolean): Observable<TodoItem>;
    public apiTodoListByListIdTodoItemByIdGet(listId: number, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TodoItem>>;
    public apiTodoListByListIdTodoItemByIdGet(listId: number, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TodoItem>>;
    public apiTodoListByListIdTodoItemByIdGet(listId: number, id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (listId === null || listId === undefined) {
            throw new Error('Required parameter listId was null or undefined when calling apiTodoListByListIdTodoItemByIdGet.');
        }
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiTodoListByListIdTodoItemByIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<TodoItem>(`${this.basePath}/api/todoList/${encodeURIComponent(String(listId))}/TodoItem/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param listId
     * @param id
     * @param todoItem
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTodoListByListIdTodoItemByIdPut(listId: number, id: number, todoItem?: TodoItem, observe?: 'body', reportProgress?: boolean): Observable<TodoItem>;
    public apiTodoListByListIdTodoItemByIdPut(listId: number, id: number, todoItem?: TodoItem, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TodoItem>>;
    public apiTodoListByListIdTodoItemByIdPut(listId: number, id: number, todoItem?: TodoItem, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TodoItem>>;
    public apiTodoListByListIdTodoItemByIdPut(listId: number, id: number, todoItem?: TodoItem, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (listId === null || listId === undefined) {
            throw new Error('Required parameter listId was null or undefined when calling apiTodoListByListIdTodoItemByIdPut.');
        }
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiTodoListByListIdTodoItemByIdPut.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<TodoItem>(`${this.basePath}/api/todoList/${encodeURIComponent(String(listId))}/TodoItem/${encodeURIComponent(String(id))}`,
            todoItem,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param listId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTodoListByListIdTodoItemGet(listId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<TodoItem>>;
    public apiTodoListByListIdTodoItemGet(listId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TodoItem>>>;
    public apiTodoListByListIdTodoItemGet(listId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TodoItem>>>;
    public apiTodoListByListIdTodoItemGet(listId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (listId === null || listId === undefined) {
            throw new Error('Required parameter listId was null or undefined when calling apiTodoListByListIdTodoItemGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<TodoItem>>(`${this.basePath}/api/todoList/${encodeURIComponent(String(listId))}/TodoItem`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param listId
     * @param todoItem
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTodoListByListIdTodoItemPost(listId: number, todoItem?: TodoItem, observe?: 'body', reportProgress?: boolean): Observable<TodoItem>;
    public apiTodoListByListIdTodoItemPost(listId: number, todoItem?: TodoItem, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TodoItem>>;
    public apiTodoListByListIdTodoItemPost(listId: number, todoItem?: TodoItem, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TodoItem>>;
    public apiTodoListByListIdTodoItemPost(listId: number, todoItem?: TodoItem, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (listId === null || listId === undefined) {
            throw new Error('Required parameter listId was null or undefined when calling apiTodoListByListIdTodoItemPost.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<TodoItem>(`${this.basePath}/api/todoList/${encodeURIComponent(String(listId))}/TodoItem`,
            todoItem,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
